### ISSUE TITLE
Online portfolio selection- Mendel framework 

### ISSUE THREAD

**Issue by andrewcztrack** [darwinex/mendel-framework#1]
Hi @Eriz11 !!
Hope your well.
I know you were looking at wrapping the mlfinlab online portfolio selection for back testing with Darwin’s. 
Are you still looking at the project.
Best,
Andrew

**Comment by Eriz11** [comment]
Hey @andrewcztrack !

The wrapper to see the mlfinlab OLPS module strategies working out in **DARWIN's** is already created :) You are free to try it out with the actual **DARWINs** and .csv but can just input or make any change that suits you.

You can find it in the [following link](https://github.com/darwinex/quant-research-env/tree/master/DARWINStrategyContentSeries), specifically in the quant-research-env. 

There are some videos coming on how to use it so be sure to subscribe to the [Darwinex channel](https://www.youtube.com/channel/UC6aYa9XjWy-HmHhyp5uN_9g) for that matter!

Best and thanks for the interest!
